### ISSUE TITLE
Download the latest version of the ChromeDriver

### ISSUE THREAD

**Issue by leandromsales** [marcellodesales/chrome-xvfb-java-gradle-docker#1]
The website http://chromedriver.storage.googleapis.com/ provides an XML that list the versions of the ChromeDriver. It is possible to get the last version of the ChromeDriver by reading the information available in the XML. See the LATEST_RELEASE

How about using this to always download the latest version of the ChromeDriver?

**Comment by marcellodesales** [comment]
Is there a link to the "LATEST_VERSION" instead?
